# 01 - Numpy
---

<img src="https://selecao.letscode.com.br/favicon.png" width="40px" style="position: absolute; top: 15px; right: 40px; border-radius: 5px;" />

## Roteiro da Aula

1. Instalação
2. Criação de arrays 1D e 2D
3. Atributos
4. Indexação e slices
5. Criação automática de arrays
6. Operações aritméticas
7. Métodos estatísticos
8. Outros métodos
9. Máscaras

## Introdução

NumPy é o pacote fundamental para computação científica em Python. É uma biblioteca Python que fornece um objeto array multidimensional, vários objetos derivados (como arrays e matrizes) e uma variedade de rotinas para operações rápidas em arrays, incluindo matemática, lógica, manipulação de *shapes*, ordenação, seleção, I/O, transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

No *core* do pacote NumPy, está o objeto ndarray. Ele consiste em arrays n-dimensionais de tipos de dados homogêneos, com muitas operações sendo executadas em código compilado para uma melhoria de desempenho. Existem várias diferenças importantes entre os arrays NumPy e as sequências padrão do Python:

- As matrizes NumPy têm um tamanho fixo na criação, ao contrário das listas Python (que podem crescer dinamicamente). Alterar o tamanho de um ndarray criará um novo array e excluirá o original.  
- Todos os elementos em uma matriz NumPy devem ser do mesmo tipo de dados e, portanto, terão o mesmo tamanho na memória. A exceção: pode-se ter arrays de objetos (do Python, incluindo NumPy), permitindo assim arrays de elementos de tamanhos diferentes.  
- Os arrays NumPy facilitam operações matemáticas avançadas e outros tipos de operações em um grande número de dados. Normalmente, essas operações são executadas com mais eficiência e com menos código do que é possível utilizando as sequências internas do Python.  
- Uma infinidade crescente de pacotes científicos e matemáticos baseados em Python estão utilizando arrays NumPy; embora eles normalmente suportem entrada de iteráveis do Python, eles convertem essa entrada em matrizes NumPy antes do processamento e geralmente produzem matrizes NumPy. Em outras palavras, para usar com eficiência muitos (talvez até a maioria) dos softwares científico/matemático baseado em Python de hoje, apenas saber usar os tipos de sequência internos do Python é insuficiente - também é necessário saber como usar matrizes NumPy.

> Fonte: [Documentação Oficial do Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html)

Um array do NumPy pode conter:

- Valores de um experimento/simulação em intervalo de tempo discreto;  
- Sinal gravado por um dispositivo de medição (sinal sonoro, por exemplo);  
- Pixels de uma imagem (nı́vel de cinza ou cor);  
- Dados 3D medidos em relação às coordenadas X, Y e Z (imagens de Ressonância Magnética, por exemplo).  


## 1. Instalação

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 16.8 MB 24.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
# Importação
import numpy as np

In [2]:
np.__version__

'1.22.0'

In [3]:
pip install -U numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## 2. Criação de Arrays 1D e 2D

In [4]:
lista = [1, 2, 3]

In [7]:
lista

[1, 2, 3]

In [9]:
print(np.array([1, 2, 3]))

[1 2 3]


In [10]:
array = np.array(lista)

In [11]:
array

array([1, 2, 3])

In [12]:
type(lista)

list

In [13]:
type(array)

numpy.ndarray

In [17]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3. Atributos

#### `ndim`

In [20]:
array

array([1, 2, 3])

In [19]:
array.ndim

1

In [21]:
matriz.ndim

2

#### `shape`

In [29]:
len(array)

3

In [22]:
array.shape

(3,)

In [26]:
array_outro = np.array([[1], [2], [3]])

In [27]:
array_outro

array([[1],
       [2],
       [3]])

In [28]:
array_outro.shape

(3, 1)

In [23]:
matriz.shape

(3, 3)

In [30]:
len(matriz)

3

#### `size`, `itemsize` e `nbytes`

In [31]:
array.size

3

In [32]:
matriz.size # Quantidade de elementos presentes no ndarray

9

In [33]:
array.itemsize

8

In [34]:
matriz.itemsize

8

In [37]:
array = np.array(lista, dtype='int32')

In [38]:
array.itemsize

4

1 byte = 8 bits = 01010101 >> 0 - 255

In [39]:
2**8

256

In [70]:
array = np.array([129, 2, 3], dtype='int8')

In [71]:
array.itemsize

1

In [72]:
array

array([-127,    2,    3], dtype=int8)

In [66]:
# 16 bits -> Menor valor: -32.00x | Maior valor: 32.00x

In [74]:
array.nbytes # Retorna quantidade de bytes reservada para o seu array (inteiro!)

3

#### `dtype`

In [35]:
array.dtype

dtype('int64')

In [36]:
matriz.dtype

dtype('int64')

## 4. Indexação e slices 

In [76]:
array = np.array([1, 2, 3])

In [77]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
array[0]

1

In [79]:
array[:2]

array([1, 2])

In [80]:
array[-1]

3

In [82]:
matriz[0] # Primeira linha da matriz (array)

array([1, 2, 3])

In [83]:
lista_mtx = [[1, 2], [3, 4]]

In [84]:
lista_mtx[1][1]

4

In [85]:
lista_mtx[1,1]

TypeError: list indices must be integers or slices, not tuple

In [87]:
matriz[1][1]

5

In [86]:
matriz[1,1]

5

In [88]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
# matriz[linha, coluna]
matriz[1:,1]

array([5, 8])

In [97]:
matriz[1:,:2]

array([[4, 5],
       [7, 8]])

In [96]:
matriz[1:,:-1]

array([[4, 5],
       [7, 8]])

## 5. Criação Automática de Arrays

#### `arange`

In [101]:
list(range(10))
list(range(0, 10))
list(range(0, 10, 1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
np.arange(0, 4, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9])

### Constantes dentro do NumPy

In [105]:
np.pi

3.141592653589793

In [106]:
np.e

2.718281828459045

In [107]:
np.inf

inf

In [108]:
np.nan

nan

#### `linspace`

In [109]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [114]:
np.linspace(0, 100, 5, endpoint=False)

array([ 0., 20., 40., 60., 80.])

#### `zeros`

In [115]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
lalala = np.zeros((2, 3, 1))

In [123]:
lalala.shape

(2, 3, 1)

In [124]:
lalala

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [130]:
np.zeros((5, 5)) + 25

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])

#### `ones`

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [127]:
np.ones((3, 2, 1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [129]:
np.ones((5, 5)) * 25

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])

#### `full`

In [131]:
np.full(10, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [132]:
np.full((5, 5), 25)

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

#### `full_like`

In [133]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
np.full_like(matriz, ))np.arange(3

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [136]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### `rand`

In [3]:
import random

In [2]:
import numpy as np

In [7]:
np.random.rand(10)

array([0.49508012, 0.2786    , 0.65799789, 0.57806841, 0.70199106,
       0.47408794, 0.61037511, 0.13247294, 0.47651114, 0.28559877])

In [6]:
np.random.rand(10, 2)

array([[0.91400698, 0.6001377 ],
       [0.38310109, 0.81691229],
       [0.27044961, 0.41992528],
       [0.70070805, 0.94089794],
       [0.43866435, 0.67590359],
       [0.85569597, 0.46053794],
       [0.23683425, 0.21200209],
       [0.93982992, 0.56137582],
       [0.9379236 , 0.47399477],
       [0.80137871, 0.66510383]])

#### `randn`

In [8]:
np.random.randn(1000)

array([-1.07076932e-01, -8.79521799e-01, -7.55712857e-01, -1.26862095e+00,
       -4.93043334e-01,  6.58766998e-01, -1.56513458e+00, -1.06068594e+00,
       -1.14729529e+00,  5.24802182e-02, -4.74465684e-01, -6.56112357e-01,
        5.73668385e-01,  1.94682284e+00,  6.75599713e-01,  1.70022351e+00,
        5.27542031e-01, -1.78354208e-01,  6.60947107e-01,  4.87558668e-01,
       -1.57210128e-01,  1.07193018e+00, -8.76949527e-01, -3.22061861e-01,
       -2.24000447e+00, -1.66324758e+00, -6.10088425e-01, -1.28608860e+00,
        1.64574880e+00, -2.40962372e-01,  1.50092172e+00,  6.04111687e-01,
       -3.01981971e-01,  6.43360187e-01, -4.41655302e-01,  2.54019893e-01,
       -7.50980435e-01, -1.13041642e-01,  5.50673619e-01,  5.80617393e-01,
       -5.38731939e-01, -4.94251701e-01,  3.93575235e-01,  6.47436731e-01,
       -7.69716070e-01, -8.58206066e-01, -8.19133621e-01, -1.07178730e+00,
        8.69162183e-01,  5.77467442e-02, -7.66712938e-01,  2.58298801e-01,
        5.21670517e-02, -

In [9]:
np.random.randn(3, 3)

array([[ 0.55494   ,  0.4122126 ,  0.70159153],
       [-2.00929169,  0.77587166,  0.66229606],
       [-0.6400271 , -0.46515158, -0.61236476]])

#### `randint`

In [15]:
# np.random.randint(min, max, qtd_elementos)

np.random.randint(1, 11, 20)

array([10,  7,  7,  4,  1,  7,  4,  4,  3,  9,  9,  5,  6,  4,  8,  8,  1,
        4,  9,  1])

In [16]:
np.random.randint(1, 11, (3, 4))

array([[ 4,  6,  1,  3],
       [ 3,  1,  4,  6],
       [10,  2,  8,  9]])

In [18]:
np.random.rand(3, 3) * 10

array([[8.75498657, 2.81009647, 8.99935381],
       [6.91047419, 5.25869216, 3.67635164],
       [7.48678855, 2.8570676 , 7.41876249]])

#### `uniform`

In [24]:
np.random.uniform(1, 10, (3, 2))

array([[5.44706322, 5.72017295],
       [1.6217112 , 1.28631091],
       [5.08965825, 4.52365705]])

In [22]:
round(10.2312312334, 3)

10.231

In [23]:
np.around(np.random.uniform(1, 10, 10), decimals=3)

array([8.399, 6.842, 4.909, 1.621, 8.016, 4.821, 1.269, 1.753, 6.836,
       4.226])

In [26]:
np.random.choice(np.array([1, 2, 3]))

2

#### `identity`

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### `diag`

In [28]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
matriz = np.array([[1, 2], [3, 4]])

In [32]:
matriz.diagonal()

array([1, 4])

In [34]:
np.diagonal(matriz)

array([1, 4])

In [38]:
np.diag([1, 2], k=-1)
np.diag([1, 2], k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

## 6. Operações entre arrays

In [39]:
array = np.arange(1, 10)

In [40]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
array + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
array - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
array * 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
array / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [46]:
arr1 + arr2

array([5, 7, 9])

In [47]:
arr3 = np.array([7, 8])

In [48]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [50]:
arr2 - arr1

array([3, 3, 3])

In [51]:
arr1 * arr2

array([ 4, 10, 18])

In [52]:
matriz

array([[1, 2],
       [3, 4]])

In [53]:
matriz2 = np.array([[1, 2], [3, 4], [5, 6]])

In [55]:
matriz * matriz2

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [56]:
matriz

array([[1, 2],
       [3, 4]])

In [57]:
matriz2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# Não dá certo!
# (2, 2) x (3, 2)
matriz @ matriz2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [60]:
# (3, 2) x (2, 2)
# Resultado: (3, 2)
matriz2 @ matriz

array([[ 7, 10],
       [15, 22],
       [23, 34]])

### Funções Matemáticas do NumPy

> https://numpy.org/doc/stable/reference/routines.math.html

In [61]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
np.cos(array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [64]:
np.exp(array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [65]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [66]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [68]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.cumsum(array)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

## 7. Métodos estatísticos e outros

#### `sum`

In [69]:
sum([1, 2, 3])

6

In [70]:
np.sum(array)

45

In [71]:
array.sum()

45

In [96]:
matriz

array([[1, 2],
       [3, 4]])

In [97]:
np.sum(matriz)

10

In [101]:
np.sum(matriz, axis=0)

array([4, 6])

In [102]:
np.sum(matriz, axis=1)

array([3, 7])

#### `max` e `argmax`

In [72]:
array.max()

9

In [73]:
np.max(array)

9

In [74]:
array.argmax()

8

In [75]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### `min` e `argmin`

In [76]:
array.min()

1

In [77]:
array.argmin()

0

#### `mean`

In [78]:
np.mean(array)

5.0

In [79]:
array.mean()

5.0

#### Biblioteca de Estatística

> `statistics`

In [81]:
import statistics as st

In [85]:
array_aleatorio = np.random.randint(1, 5, 10)

array_aleatorio

array([2, 3, 2, 3, 3, 2, 1, 3, 3, 4])

In [86]:
st.mode(array_aleatorio)

3

## Outros métodos

#### `np.repeat`

In [87]:
array = np.array([1, 2, 3])

In [90]:
np.repeat(array, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [95]:
np.repeat(matriz, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

#### `np.transpose`

In [92]:
matriz

array([[1, 2],
       [3, 4]])

In [93]:
np.transpose(matriz)

array([[1, 3],
       [2, 4]])

In [94]:
matriz.T

array([[1, 3],
       [2, 4]])

#### `reshape`

In [103]:
array_aleatorio

array([2, 3, 2, 3, 3, 2, 1, 3, 3, 4])

In [104]:
array_aleatorio.shape

(10,)

In [105]:
array_aleatorio.reshape((5, 2))

array([[2, 3],
       [2, 3],
       [3, 2],
       [1, 3],
       [3, 4]])

In [106]:
array_aleatorio = np.random.randint(1, 5, 12)

In [107]:
array_aleatorio

array([4, 1, 1, 4, 3, 4, 1, 1, 1, 4, 1, 4])

In [108]:
array_aleatorio.reshape((3, 2, 2))

array([[[4, 1],
        [1, 4]],

       [[3, 4],
        [1, 1]],

       [[1, 4],
        [1, 4]]])

In [109]:
array_aleatorio

array([4, 1, 1, 4, 3, 4, 1, 1, 1, 4, 1, 4])

In [121]:
array_aleatorio.reshape((-1, 3))

array([[4, 1, 1],
       [4, 3, 4],
       [1, 1, 1],
       [4, 1, 4]])

In [117]:
array_aleatorio.reshape((-1, 1))

array([[4],
       [1],
       [1],
       [4],
       [3],
       [4],
       [1],
       [1],
       [1],
       [4],
       [1],
       [4]])

#### `np.vstack`

In [122]:
array

array([1, 2, 3])

In [124]:
np.vstack((array, array, np.array([9, 4, 7])))

array([[1, 2, 3],
       [1, 2, 3],
       [9, 4, 7]])

#### `np.hstack`

In [125]:
np.hstack((array, array))

array([1, 2, 3, 1, 2, 3])

In [126]:
matriz

array([[1, 2],
       [3, 4]])

In [130]:
array_aleatorio.reshape(-1, 4)

array([[4, 1, 1, 4],
       [3, 4, 1, 1],
       [1, 4, 1, 4]])

In [129]:
# Não é possível, porque os arrays precisam ter o mesmo shape na horizontal (mesmo número de linhas)
np.hstack((matriz, array_aleatorio.reshape(-1, 4)))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

## 8. Máscaras

In [5]:
import numpy as np

In [7]:
array_aleatorio = np.random.randint(-10, 11, 20)

array_aleatorio

array([  0,   9,   0,   9,   5,  -4,   4,  10, -10,  -4,  -6,  10,  -1,
        -7,  -1, -10,  -8,  -4,   1,  -2])

In [8]:
array_aleatorio > 0 

array([False,  True, False,  True,  True, False,  True,  True, False,
       False, False,  True, False, False, False, False, False, False,
        True, False])

In [13]:
arr = np.array([1, 2, 3])

In [14]:
arr[0]

1

In [20]:
arr_filtrado = arr[np.array([True, False, True])]

In [21]:
arr

array([1, 2, 3])

In [22]:
arr_filtrado

array([1, 3])

In [23]:
array_aleatorio

array([  0,   9,   0,   9,   5,  -4,   4,  10, -10,  -4,  -6,  10,  -1,
        -7,  -1, -10,  -8,  -4,   1,  -2])

In [24]:
mascara = array_aleatorio >= 0

In [25]:
mascara

array([ True,  True,  True,  True,  True, False,  True,  True, False,
       False, False,  True, False, False, False, False, False, False,
        True, False])

In [26]:
array_aleatorio[mascara]

array([ 0,  9,  0,  9,  5,  4, 10, 10,  1])

In [27]:
array_aleatorio[array_aleatorio >= 0]

array([ 0,  9,  0,  9,  5,  4, 10, 10,  1])

In [29]:
array_aleatorio[(array_aleatorio >= 0) & (array_aleatorio <= 5)]

array([0, 0, 5, 4, 1])

In [30]:
array_aleatorio[(array_aleatorio >= 5) | (array_aleatorio <= -5)]

array([  9,   9,   5,  10, -10,  -6,  10,  -7, -10,  -8])

In [33]:
np.bitwise_and(array_aleatorio >= 0, array_aleatorio <= 5)

array([ True, False,  True, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False])