# Aula 01 - Numpy
---

<img src="https://selecao.letscode.com.br/favicon.png" width="40px" style="position: absolute; top: 15px; right: 40px; border-radius: 5px;" />

## Roteiro da Aula

1. Instalação
2. Criação de arrays 1D e 2D
3. Atributos
4. Indexação e slices
5. Criação automática de arrays
6. Operações aritméticas
7. Métodos estatísticos
8. Outros métodos
9. Máscaras

## Introdução

NumPy é o pacote fundamental para computação científica em Python. É uma biblioteca Python que fornece um objeto array multidimensional, vários objetos derivados (como arrays e matrizes) e uma variedade de rotinas para operações rápidas em arrays, incluindo matemática, lógica, manipulação de *shapes*, ordenação, seleção, I/O, transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

No *core* do pacote NumPy, está o objeto ndarray. Ele consiste em arrays n-dimensionais de tipos de dados homogêneos, com muitas operações sendo executadas em código compilado para uma melhoria de desempenho. Existem várias diferenças importantes entre os arrays NumPy e as sequências padrão do Python:

- As matrizes NumPy têm um tamanho fixo na criação, ao contrário das listas Python (que podem crescer dinamicamente). Alterar o tamanho de um ndarray criará um novo array e excluirá o original.  
- Todos os elementos em uma matriz NumPy devem ser do mesmo tipo de dados e, portanto, terão o mesmo tamanho na memória. A exceção: pode-se ter arrays de objetos (do Python, incluindo NumPy), permitindo assim arrays de elementos de tamanhos diferentes.  
- Os arrays NumPy facilitam operações matemáticas avançadas e outros tipos de operações em um grande número de dados. Normalmente, essas operações são executadas com mais eficiência e com menos código do que é possível utilizando as sequências internas do Python.  
- Uma infinidade crescente de pacotes científicos e matemáticos baseados em Python estão utilizando arrays NumPy; embora eles normalmente suportem entrada de iteráveis do Python, eles convertem essa entrada em matrizes NumPy antes do processamento e geralmente produzem matrizes NumPy. Em outras palavras, para usar com eficiência muitos (talvez até a maioria) dos softwares científico/matemático baseado em Python de hoje, apenas saber usar os tipos de sequência internos do Python é insuficiente - também é necessário saber como usar matrizes NumPy.

> Fonte: [Documentação Oficial do Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html)

Um array do NumPy pode conter:

- Valores de um experimento/simulação em intervalo de tempo discreto;  
- Sinal gravado por um dispositivo de medição (sinal sonoro, por exemplo);  
- Pixels de uma imagem (nı́vel de cinza ou cor);  
- Dados 3D medidos em relação às coordenadas X, Y e Z (imagens de Ressonância Magnética, por exemplo).  


## 1. Instalação

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 16.8 MB 24.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
# Importação
import numpy as np

In [2]:
np.__version__

'1.22.0'

In [3]:
pip install -U numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## 2. Criação de Arrays 1D e 2D

In [4]:
lista = [1, 2, 3]

In [7]:
lista

[1, 2, 3]

In [9]:
print(np.array([1, 2, 3]))

[1 2 3]


In [10]:
array = np.array(lista)

In [11]:
array

array([1, 2, 3])

In [12]:
type(lista)

list

In [13]:
type(array)

numpy.ndarray

In [17]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3. Atributos

#### `ndim`

In [20]:
array

array([1, 2, 3])

In [19]:
array.ndim

1

In [21]:
matriz.ndim

2

#### `shape`

In [29]:
len(array)

3

In [22]:
array.shape

(3,)

In [26]:
array_outro = np.array([[1], [2], [3]])

In [27]:
array_outro

array([[1],
       [2],
       [3]])

In [28]:
array_outro.shape

(3, 1)

In [23]:
matriz.shape

(3, 3)

In [30]:
len(matriz)

3

#### `size`, `itemsize` e `nbytes`

In [31]:
array.size

3

In [32]:
matriz.size # Quantidade de elementos presentes no ndarray

9

In [33]:
array.itemsize

8

In [34]:
matriz.itemsize

8

In [37]:
array = np.array(lista, dtype='int32')

In [38]:
array.itemsize

4

1 byte = 8 bits = 01010101 >> 0 - 255

In [39]:
2**8

256

In [70]:
array = np.array([129, 2, 3], dtype='int8')

In [71]:
array.itemsize

1

In [72]:
array

array([-127,    2,    3], dtype=int8)

In [66]:
# 16 bits -> Menor valor: -32.00x | Maior valor: 32.00x

In [74]:
array.nbytes # Retorna quantidade de bytes reservada para o seu array (inteiro!)

3

#### `dtype`

In [35]:
array.dtype

dtype('int64')

In [36]:
matriz.dtype

dtype('int64')

## 4. Indexação e slices 

In [76]:
array = np.array([1, 2, 3])

In [77]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
array[0]

1

In [79]:
array[:2]

array([1, 2])

In [80]:
array[-1]

3

In [82]:
matriz[0] # Primeira linha da matriz (array)

array([1, 2, 3])

In [83]:
lista_mtx = [[1, 2], [3, 4]]

In [84]:
lista_mtx[1][1]

4

In [85]:
lista_mtx[1,1]

TypeError: list indices must be integers or slices, not tuple

In [87]:
matriz[1][1]

5

In [86]:
matriz[1,1]

5

In [88]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
# matriz[linha, coluna]
matriz[1:,1]

array([5, 8])

In [97]:
matriz[1:,:2]

array([[4, 5],
       [7, 8]])

In [96]:
matriz[1:,:-1]

array([[4, 5],
       [7, 8]])

## 5. Criação Automática de Arrays

#### `arange`

In [101]:
list(range(10))
list(range(0, 10))
list(range(0, 10, 1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
np.arange(0, 4, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9])

### Constantes dentro do NumPy

In [105]:
np.pi

3.141592653589793

In [106]:
np.e

2.718281828459045

In [107]:
np.inf

inf

In [108]:
np.nan

nan

#### `linspace`

In [109]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [114]:
np.linspace(0, 100, 5, endpoint=False)

array([ 0., 20., 40., 60., 80.])

#### `zeros`

In [115]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
lalala = np.zeros((2, 3, 1))

In [123]:
lalala.shape

(2, 3, 1)

In [124]:
lalala

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [130]:
np.zeros((5, 5)) + 25

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])

#### `ones`

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [127]:
np.ones((3, 2, 1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [129]:
np.ones((5, 5)) * 25

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])

#### `full`

In [131]:
np.full(10, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [132]:
np.full((5, 5), 25)

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

#### `full_like`

In [133]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
np.full_like(matriz, np.arange(3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [136]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### `rand`

#### `randn`

#### `randint`

#### `uniform`

#### `identity`

#### `diag`

## 6. Operações entre arrays

## 7. Métodos estatísticos e outros

#### `sum`

#### `max` e `argmax`

#### `min` e `argmin`

#### `mean`

## Outros métodos

#### `np.repeat`

#### `np.transpose`

#### `reshape`

#### `np.vstack`

#### `np.hstack`

## 8. Máscaras